# Generated by Django 5.0.3 on 2024-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="содержимое"),
        ),
    ]
