# Generated by Django 5.0.3 on 2024-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="email",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Почта"
            ),
        ),
    ]
