# Generated by Django 5.0.3 on 2024-04-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("set_published_product", "Can set published product"),
                    ("change_description_product", "Can change description product"),
                    ("change_category", "Can change category"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
